In [1]:
import pandas as pd
import numpy as np

train = pd.read_csv(r"C:\Users\DELL\Desktop\Kaggle\Customer Churn\train.csv")
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [4]:
ids = train['id']
train.drop('id', axis = 1, inplace= True)
train.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,No,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,Yes,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,Female,0,No,No,1,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,Female,0,No,No,1,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [10]:
X = train.drop('Churn', axis=1)
y = train['Churn']

In [13]:
y = y.map({'Yes' :1, 'No':0})
y.unique()

array([0, 1])

In [22]:
numerical_features = [i for i in X.select_dtypes(exclude='object').columns]
numerical_features.remove('SeniorCitizen')
print("Numerical Features: " , len(numerical_features), numerical_features)
categorical_features = [i for i in X.select_dtypes(include='object').columns]
print("Categorical Features: " , len(categorical_features), categorical_features)

Numerical Features:  3 ['tenure', 'MonthlyCharges', 'TotalCharges']
Categorical Features:  15 ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [24]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

preprocessing = ColumnTransformer([
    ('onehot', OneHotEncoder(), categorical_features),
    ('scaler', StandardScaler(), numerical_features)
])

X_train_preprocessed = preprocessing.fit_transform(X_train)
X_train_preprocessed

array([[ 1.        ,  0.        ,  0.        , ...,  1.21393639,
         0.55098917,  1.18769399],
       [ 1.        ,  0.        ,  1.        , ...,  0.41588312,
        -1.49315831, -0.6651811 ],
       [ 0.        ,  1.        ,  0.        , ...,  1.13413106,
         1.1046795 ,  1.84624777],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.38217015,
        -1.4706244 , -0.82774975],
       [ 1.        ,  0.        ,  0.        , ...,  1.01442307,
         0.08743446,  0.66375079],
       [ 0.        ,  1.        ,  0.        , ...,  1.37354704,
         1.26241687,  1.98922242]], shape=(475355, 44))

In [25]:
X_test_preprocessed = preprocessing.transform(X_test)
X_test_preprocessed

array([[ 1.        ,  0.        ,  0.        , ...,  1.37354704,
         0.75862304,  1.61228731],
       [ 1.        ,  0.        ,  0.        , ...,  0.29617513,
         0.31116399,  0.59125511],
       [ 0.        ,  1.        ,  0.        , ...,  0.6552991 ,
        -1.48511048, -0.60215337],
       ...,
       [ 0.        ,  1.        ,  0.        , ...,  0.81490975,
         0.95016127,  1.29173538],
       [ 1.        ,  0.        ,  1.        , ..., -0.94080744,
         0.14859793, -0.66749502],
       [ 1.        ,  0.        ,  1.        , ..., -0.86100211,
         0.19527531, -0.66600901]], shape=(118839, 44))

In [26]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)
X_train_pca = pca.fit_transform(X_train_preprocessed)
X_test_pca = pca.transform(X_test_preprocessed)

In [27]:
X_train_pca.shape, X_test_pca.shape

((475355, 17), (118839, 17))